[server]
headless = true
port = 8501
enableCORS = false

[logger]
level = "debug"

[browser]
serverAddress = "0.0.0.0"

[theme]
primaryColor = "#ff4b4b"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f0f0"
textColor = "#262730"
